id: 9242876a-41c4-42f8-96f8-ac92d6025406
title: Settings
data:
  site_name: 'Nick Lewis'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/nicklewis'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/nickeblewis'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:nickeblewis@gmail.com'
      icon: site/social-icons/email.svg
    -
      name: Instagram
      url: 'https://instagram.com/nicklewisphotography'
      icon: site/social-icons/instagram.svg
